# Generated by Django 4.0.6 on 2022-07-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_channnels_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='channnel_name',
            new_name='channel_name',
        ),
    ]
