# Generated by Django 4.0.6 on 2022-08-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_box_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-customer__id']},
        ),
        migrations.AlterModelOptions(
            name='channels',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='channels',
            name='total_price',
        ),
    ]
