# Generated by Django 4.0.6 on 2022-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_box_options_alter_channels_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='customer',
        ),
        migrations.AddField(
            model_name='channels',
            name='customer',
            field=models.ManyToManyField(to='store.customer'),
        ),
    ]
